---
- name: Create Docker network
  docker_network:
    name: yolo-network
    driver: bridge
  become: yes

- name: Pull MongoDB image
  docker_image:
    name: mongo:4.4
    source: pull
   

- name: Create MongoDB container
  docker_container:
    name: mongodb
    image: mongo:4.4
    networks:
      - name: yolo-network
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart_policy: always
 