---
- name: Pull Backend image
  docker_image:
    name: scolasticah/yolo_backend
    source: pull
   

- name: Create Backend container
  docker_container:
    name: yolo_backend
    image: scolasticah/yolo_backend
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    restart_policy: always
    env:
      MONGO_URL: mongodb://mongo:27017/yolomy
    
 
