---
- name: Pull Client image
  docker_image:
    name: scolasticah/yolo_client
    source: pull
   

- name: Create Client container
  docker_container:
    name: yolo_client
    image: scolasticah/yolo_client
    networks:
      - name: app-net
    ports:
      - "3000:3000"
    
    env:
      REACT_APP_BACKEND_URL: http://backend:5000/api
    restart_policy: always

